# ===================================================================
# SERVER CONFIGURATION
# ===================================================================
server:
  # A unique port for the storefront-service to avoid conflicts.
  port: 8086

# ===================================================================
# CORE SPRING APPLICATION CONFIGURATION
# ===================================================================
spring:
  application:
    name: lemicare-cms

  # ===================================================================
  # FILE UPLOAD CONFIGURATION (Fix for 413 Payload Too Large)
  # ===================================================================
  servlet:
    multipart:
      max-file-size: 50MB        # 🔸 Maximum file size allowed for upload
      max-request-size: 50MB     # 🔸 Maximum total multipart/form-data request size

  # ===================================================================
  # SECURITY CONFIGURATION (OAUTH2 RESOURCE SERVER)
  # ===================================================================
  security:
    oauth2:
      resourceserver:
        jwt:
          # This is used to validate the 'iss' (issuer) claim inside the JWT.
          # It MUST be the same value as 'app.jwt.issuer' in your auth-service.
          issuer: "https://smartbridgein.com"

          # This provides the shared secret to validate the JWT's signature.
          # It MUST be the exact same 'app.jwt.secret-key' from your auth-service.
          # In production, this MUST be loaded from an environment variable.
          secret-key: "YourSuperStrongAndLongSecretKeyForHmacShaAlgorithmsAtLeast256Bits"

          audience: "MS"

# ===================================================================
# OPENAPI / SWAGGER DOCUMENTATION CONFIGURATION
# ===================================================================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  info:
    title: "Lemicare -CMS Service API"
    version: "1.0.0"
    description: "APIs for managing e-commerce content (products, categories, images) and public storefront data."
  # Defines default content types for the API
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# ===================================================================
# CUSTOM APPLICATION PROPERTIES
# ===================================================================
app:
  firebase:
    # Path to the service account key within the classpath.
    service-account-path: "google-services.json"

# ===================================================================
# DOWNSTREAM SERVICE LOCATIONS
# ===================================================================
# Centralized configuration for the URLs of other microservices this
# service needs to communicate with.
services:
  inventory:
    # We point to the API Gateway's address, as it's the single entry point.
    # The RestTemplate client will use this base URL.
    url: "https://lemicare-inventory-service-511338430385.asia-south1.run.app/api/inventory"

  payment-service:
    # The base URL of the storefront-service.
    # Feign will use this to construct the full request URL.
    url: "https://lemicare-payment-service-511338430385.asia-south1.run.app" # <-- Port of your storefront-service

# ===================================================================
# ACTUATOR / MANAGEMENT ENDPOINTS
# ===================================================================
management:
  endpoints:
    web:
      exposure:
        # Expose the 'health' and 'info' endpoints for monitoring.
        include: "health,info"
  endpoint:
    health:
      show-details: when_authorized

# ===================================================================
# GOOGLE CLOUD STORAGE CONFIGURATION
# ===================================================================
gcp:
  project-id: lemicareprod
  storage:
    bucket-name: my-app-bucket-cmsservice  # Your GCS bucket name for product images
